Repository nbc-final-team2/ddaraogae, pull requests merged in 2024-06, with the labels that each got.

#6 Entity 추가 및 기본 Repository 구성
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/DogEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/SpotEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StampEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/WalkingEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/DogRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/SpotRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/StampRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/WalkingRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/WeatherRepository.kt
Labels: ✨ feature

#12 Data layer 베이스 코드 작성 후 병합
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/DogDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/SpotDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/StampDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/WalkingDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/DogRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/SpotRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StampRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/WalkingRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StampEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/WalkingEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/DogRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/SpotRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/StampRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/WalkingRepository.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ✨ feature

#17 지도 세팅, client_id 입력 방법
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/res/layout/activity_walk.xml
  app/src/main/res/layout/fragment_walk.xml
  app/src/main/res/values/client_id.xml
  settings.gradle.kts
Labels: ⚙️ chore, 🖌️ design

#20 기본 이메일, 구글 로그인 및 회원가입 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/EmailAuthEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/UserEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/AuthRepository.kt
  gradle/libs.versions.toml
Labels: ⚙️ chore, ✨ feature

#19 [design] login xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/onboard/InputImageFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/onboard/InputInfoFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/onboard/InputNameFragment.kt
  app/src/main/res/drawable/login_box.xml
  app/src/main/res/drawable/login_google.png
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_input_image.xml
  app/src/main/res/values/strings.xml
Labels: 🖌️ design, 🎨 resource

#22 날씨 API 연동 구현
  app/build.gradle.kts
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/Key.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/RetrofitClient.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/RetrofitDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/RetrofitInterceptor.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/DustDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/WeatherDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/WeatherRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/WeatherEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/WeatherRepository.kt
  app/src/test/java/com/nbcfinalteam2/ddaraogae/WeatherRepositoryImplTest.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: ✨ feature

#28 Feature/add map into finish activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/res/layout/activity_finish.xml
  app/src/main/res/layout/fragment_walk.xml
Labels: ✨ feature, 🛠️ refactor

#31 MainActivity의 Navigation Bottom 메뉴 바 구현
  app/build.gradle.kts
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/res/color/nav_selector_color.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_walk.xml
  app/src/main/res/drawable/rec_main_nav.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/menu/nav_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ feature

#34 Feature/remove data binding
  app/build.gradle.kts
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/res/layout/activity_walk.xml
Labels: ⚙️ chore

#37 산책그래프 초기 출력세팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/res/drawable/bg_walk_graph_no_data.xml
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🖌️ design, ✨ feature, 🎨 resource

#42 HIlt 적용 및 리팩터링
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/DdaraogaeApplication.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/DataSourceModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/FirebaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/NetworkModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/RepositoryModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/RetrofitClient.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/WeatherApiService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/FirebaseMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/DogRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StampRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/WalkingRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/WeatherRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/DeleteDogUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetCurrentUserUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetDogByIdUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetDogListUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampNumByDogIdAndPeriodUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetWalkingByIdUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetWalkingListByDogIdAndPeriodUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetWeatherDataUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertDogUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertStampUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertWalkingDataUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/SignInWithEmailUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/SignInWithGoogleUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/SignOutUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/SignUpWithEmailUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateDogUseCaseImpl.kt
  app/src/test/java/com/nbcfinalteam2/ddaraogae/WeatherRepositoryImplTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ⚙️ chore, ✨ feature, 🛠️ refactor

#49 [Feat] google 로그인
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#48 spot을 위한 검색 api 구현
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/NetworkModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/RepositoryModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/KakaoInterceptor.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/Key.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/SearchApiService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/WeatherInterceptor.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/StoreDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/StoreMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StoreRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StoreEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/StoreRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetHospitalStoreDataUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetHospitalStoreDataUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStoreDataUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStoreDataUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/TestViewModel.kt
Labels: ✨ feature

#51 날씨 ui 상에 지역을 표시할 수 있도록 좌표-주소 변환 api 구현
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/NetworkModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/CityApiService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/SearchApiService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/retrofit/WeatherApiService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/CityDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/DustDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/StoreDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/WeatherDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/StoreMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/WeatherRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/WeatherEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/WeatherRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/TestViewModel.kt
  app/src/test/java/com/nbcfinalteam2/ddaraogae/WeatherRepositoryImplTest.kt
Labels: ✨ feature

#56 좌표 간 거리 계산 로직 구현
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DistanceCalculator.kt
Labels: ✨ feature

#55 백그라운드에서 위치 수집하도록 Service 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/LocationService.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ⚙️ chore, ✨ feature, 🎨 resource

#59 Data 및 Domain 모델 프로퍼티 nullable 처리
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/FirebaseMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/DogEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/EmailAuthEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/LatLngEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StampEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/UserEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/WalkingEntity.kt
Labels: 🛠️ refactor

#64 nullable 처리 하면서 발생한 오류 픽스
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/DogRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/EmailAuthEntity.kt
Labels: 🐞 bug

#62 이메일 인증 및 회원 탈퇴 기능 구현
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/AuthRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/DeleteAccountUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/DeleteAccountUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/IsCurrentUserEmailVerifiedUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/IsCurrentUserEmailVerifiedUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/SendVerificationEmailUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/SendVerificationEmailUseCaseImpl.kt
Labels: ✨ feature

#69 StoreEntity에 위경도 데이터가 추가되도록 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/StoreDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/StoreMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StoreEntity.kt
Labels: 🍞 etc, 🛠️ refactor

#70 이미지 저장 로직 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/FirebaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/DogRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/DogRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertDogUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertDogUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateDogUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateDogUseCaseImpl.kt
  gradle/libs.versions.toml
Labels: ✨ feature

#76 tracking, polyline, spot 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/LocationService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/TestViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkTestViewModel.kt
  app/src/main/res/values/client_id.xml
Labels: ✨ feature, 🛠️ refactor

#78 스탬프 조건 확인 및 저장 기능 구현
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/DataUtil.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/StampInfo.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/FirebaseMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StampRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StampEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/StampRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/CheckStampConditionUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/CheckStampConditionUseCaseImpl.kt
Labels: ✨ feature, 🛠️ refactor

#81 Location Service 내에서 거리 계산하도록 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/LocationService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DistanceCalculator.kt
Labels: 🐞 bug, ✨ feature, 🛠️ refactor

#87 [feature]walk 거리, 시간 측정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkTestViewModel.kt
  app/src/main/res/layout/activity_finish.xml
  app/src/main/res/layout/fragment_walk.xml
Labels: ✨ feature

#84 경로가 그려진 지도 이미지를 저장하여 firebase에 저장(기존 기능 수정)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/WalkingDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/FirebaseMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/WalkingRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/WalkingEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/WalkingRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertWalkingDataUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertWalkingDataUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/WalkingInfo.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/TestViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
Labels: ✨ feature

#88 반려견 추가/수정 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/DogRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/DogRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertDogUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertDogUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateDogUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateDogUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/model/DogItemModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailDogUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/UriToByteArrayConvertor.kt
  app/src/main/res/layout/activity_add.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_edit_pet.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_edit_pet_dog_selection.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature, 🛠️ refactor

#97 산책 화면 반려견 선택 인터페이스 추가, 산책화면 리팩터링 후 병합
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/StoreModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/WalkingUiModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/LocationService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/ServiceInfoState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkDogAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkViewModel.kt
  app/src/main/res/layout/activity_walk.xml
  app/src/main/res/layout/fragment_walk.xml
  app/src/main/res/layout/item_walk_dogs.xml
  app/src/main/res/values/dimens.xml
Labels: 🖌️ design, ✨ feature, 🛠️ refactor, 🎨 resource

#99 반려견 상세 목록, 수정 화면 리팩터링(UI에 자연스럽게 반영되도록 수정)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/UpdateTaskState.kt
Labels: 🛠️ refactor

#95 [Refactor]회원가입, 로그인
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/AuthRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/res/drawable/signup_authentication.xml
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature, 🛠️ refactor

#102 [feature]splash 화면
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/doglogo.png
  app/src/main/res/values/styles.xml
Labels: 🖌️ design, ✨ feature

#106 [feature]개인정보 방침 페이지 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypagePrivacyActivity.kt
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_privacy.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/privacy.xml
  app/src/main/res/values/strings.xml
Labels: 🖌️ design, ✨ feature

#105 [fix] 로그인 에러 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
Labels: 🐞 bug

#103 [design] 앱 로고 변경
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: 🖌️ design, 🎨 resource

#110 스탬프 관련 비즈니스 로직 변경
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StampRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/StampRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampListByPeriodUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampListByPeriodUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampNumByDogIdAndPeriodUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampNumByDogIdAndPeriodUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampNumByPeriodUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampNumByPeriodUseCaseImpl.kt
Labels: ✨ feature, 🛠️ refactor

#109 Feature/perssion,markercontent
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
Labels: ✨ feature, 🛠️ refactor

#121 Feature/refactoring marker,location overlay circle
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/res/drawable/locationcircle.xml
  app/src/main/res/drawable/spotmarker.xml
Labels: ✨ feature, 🛠️ refactor, 📋 style

#114 지도 크기 유동적으로 변하도록 변경
  app/src/main/res/layout/fragment_walk.xml
Labels: 🖌️ design

#119 유저 삭제 로직 변경
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/TestViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
Labels: 🛠️ refactor

#117 [feature] 홈 어뎁터 수정 , 디테일 펫 버튼 안보이는 문제 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/DogProfileAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/fragment_home.xml
Labels: ✨ feature

#122 산책 완료 화면 구현 + polyline 그려진 것에 적절하게 zoom 된 상태의 지도 그리기 구현
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StampRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StampEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/StampRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/CheckStampConditionUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/CheckStampConditionUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/LocationService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishDogAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishStampAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/StampDialogFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/TaskState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/ImageConverter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/TextConverter.kt
  app/src/main/res/drawable/ic_stamp.xml
  app/src/main/res/layout/activity_finish.xml
  app/src/main/res/layout/fragment_stamp_dialog_.xml
  app/src/main/res/layout/item_finish_dogs.xml
  app/src/main/res/layout/item_walk_finish_stamp.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#116 home 위치 정보 권한 설정및 산책 기록 기능 구현
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/WalkingInfo.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/WalkHistoryAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_history_walk.xml
Labels: 🐞 bug, ✨ feature

#126 날씨 갱신, 다이얼로그 클릭이벤트 추가및 차트, 산책기록 버그 수정
  app/build.gradle.kts
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/CalendarDialog.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/WalkHistoryAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/WalkHistoryMapDialog.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
  app/src/main/res/drawable/ic_history_map.xml
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/dialog_calendar.xml
  app/src/main/res/layout/dialog_walk_history_map.xml
  app/src/main/res/layout/item_home_history_walk.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐞 bug, ⚙️ chore, 🖌️ design, ✨ feature

#125 Walk쪽 예외처리 전면 리팩터링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/DeviceStateManagerModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/LocationService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkEvent.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/ToastMaker.kt
  app/src/main/res/values/strings.xml
Labels: ⚙️ chore, 🍞 etc, ✨ feature, 🛠️ refactor, 🎨 resource

#128 산책 데이터 업로드 로직 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
Labels: 🐞 bug

#131 서비스 버그 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/LocationService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
Labels: 🐞 bug

#132 앱 상태바, 네비게이션바 통일 수정 완료
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypagePrivacyActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
Labels: 🖌️ design

#135 회원탈퇴 버그 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
Labels: 🐞 bug

#137 반려견 추가 화면 리팩터링
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/DefaultEvent.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/SharedEvent.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/SharedEventViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🛠️ refactor

#138 Fix/home and history
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/DogProfileAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/WalkHistoryAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypagePrivacyActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishDogAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkDogAdapter.kt
  app/src/main/res/drawable/ic_dog_default_thumbnail.png
  app/src/main/res/layout/activity_add.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_edit_pet.xml
  app/src/main/res/layout/item_edit_pet_dog_selection.xml
  app/src/main/res/layout/item_finish_dogs.xml
  app/src/main/res/layout/item_home_dog_selection.xml
  app/src/main/res/layout/item_home_history_walk.xml
  app/src/main/res/layout/item_walk_dogs.xml
Labels: 🐞 bug, 🖌️ design, ✨ feature

#140 네트워크 예외처리및 model통합 완료
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/DogInfo.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/WalkingInfo.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/WalkingUiModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/model/DogItemModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailDogUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkDogAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
Labels: ✨ feature, 🛠️ refactor

#141 SharedViewModel 일부 적용 후 병합
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/SharedEventViewModelModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/SharedEvent.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/SharedEventViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/DogProfileAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
Labels: 🐞 bug, 🛠️ refactor

#142 Detail 로직 리팩터링
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/WalkHistoryAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/TestViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailDogUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/PrivacyFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/UpdateTaskState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/StampDialogFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/TaskState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkTestViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🐞 bug, 🛠️ refactor

#148 로그인 회원가입 디자인 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_home.xml
Labels: 🐞 bug, 🖌️ design

#154 네이버 현재 위치 버튼 비활성화 하고 커스텀한 버튼 추가하기
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/res/drawable/locationbutton.xml
  app/src/main/res/layout/fragment_walk.xml
Labels: 🛠️ refactor

#156 이벤트 공유 뷰모델 이용 로직 리팩터링
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/DispatcherModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/EventBusModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/bus/ItemChangedEventBus.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/ItemChangedEventBusImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/SharedEvent.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/SharedEventViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
Labels: 🛠️ refactor

#155 로딩 기능 추가및 로그인화면 UI 버그 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/loading/LoadingDialog.kt
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/dialog_loading.xml
Labels: 🖌️ design, ✨ feature

#163 refactor/viewModel
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
Labels: 🛠️ refactor

#166 반려견 리스트 이름 순 정렬해서 로드, 불필요 파일 삭제, Hilt 모듈 내 누락 어노테이션 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/DataSourceModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/DeviceStateManagerModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/FirebaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/NetworkModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/RepositoryModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/LocationService.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/DetailActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailDogUiState.kt
  app/src/main/res/layout/activity_detail.xml
Labels: 🛠️ refactor

#165 Home에서 ViewModel 내에서 context 호출 해 getString() 하는 부분 View로 빼내기
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/WeatherInfo.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
Labels: 🛠️ refactor

#173 fix: conflict markresolved하고 if문이 빠져서 빌드 안되는 문제 해결
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
Labels: 🛠️ refactor

#158 강아지 추가/수정 시 썸네일 이미지를 기본 이미지로 변경할 수 있도록 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditUiState.kt
  app/src/main/res/drawable/ic_dog_default_thumbnail.png
  app/src/main/res/drawable/ic_dog_default_thumbnail.xml
  app/src/main/res/drawable/ic_remove.xml
  app/src/main/res/layout/activity_add.xml
  app/src/main/res/layout/activity_edit_pet.xml
  app/src/main/res/values/strings.xml
Labels: 🖌️ design, ✨ feature

#170 예외처리 리팩터링
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetCurrentUserUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetCurrentUserUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/SignOutUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/SignOutUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/DefaultEvent.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/loading/LoadingDialog.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/TaskState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/res/values/strings.xml
Labels: 🛠️ refactor

#175 산책 UI에 반려견 이름 표시하도록 기능 추가
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkDogAdapter.kt
  app/src/main/res/layout/item_walk_dogs.xml
Labels: 🖌️ design, ✨ feature

#178 기존 DefaultEvent.Loading 잔재 코드 제거
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt
Labels: 🐞 bug

#179 기존 로딩 처리 삭제
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/UpdateTaskState.kt
Labels: 🐞 bug

#167 산책기록 UI, history 앱 진입시 기본값설정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/WalkHistoryAdapter.kt
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/item_home_history_walk.xml
Labels: 🖌️ design, ✨ feature

#172 로그인 인증 버그 수정 / 서비스 이용약관, 개인정보수집동의 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageAgreementPrivacy.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageTermsActivity.kt
  app/src/main/res/drawable/agreement_privacy_policy_1.png
  app/src/main/res/drawable/terms_of_use_1.png
  app/src/main/res/drawable/terms_of_use_2.png
  app/src/main/res/drawable/terms_of_use_3.png
  app/src/main/res/drawable/terms_of_use_4.png
  app/src/main/res/drawable/terms_of_use_5.png
  app/src/main/res/drawable/terms_of_use_6.png
  app/src/main/res/layout/activity_agreement_privacy.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_terms_of_use.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 bug, 🖌️ design, ✨ feature

#185 릴리즈용 앱 서명키 적용을 위한 준비
  .gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
Labels: 📗 docs, 🍞 etc

#183 로딩 UI 적용(1차)
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/loading/LoadingDialog.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🛠️ refactor

#187 [fix]자동 로그인 로직 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🐞 bug

#194 keystore 폴더가 git에 올리는 파일 대상이 되지 않도록 수정
  .gitignore
Labels: 🍞 etc

#196 맵 초기화 전 현재 위치 버튼 누르면 죽는 문제 해결
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
Labels: 🐞 bug

#190 날씨 예외처리, UI수정, 산책기능추가등
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/StampInfo.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/bus/ItemChangedEventBus.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/StampModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/ItemChangedEventBusImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AllStampActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AllStampAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AllStampViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/WalkHistoryAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageAgreementPrivacy.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypagePrivacyActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageTermsActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/res/drawable/progress_bar_stamp.xml
  app/src/main/res/drawable/rec_main_nav.xml
  app/src/main/res/layout/activity_all_stamp.xml
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_home_all_stamp.xml
  app/src/main/res/layout/item_home_dog_selection.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 bug, 🖌️ design, ✨ feature

#197 복수의 반려견 동반 산책 시, 중복된 스탬프 획득 버그 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishViewModel.kt
Labels: 🐞 bug

#198 로딩 UI 적용(2차)
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddUiState.kt
Labels: 🛠️ refactor

#191 [fix] 그래프 배경 색 회색 -> 흰색
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/GraphUtils.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
Labels: 🖌️ design

#201 패키지 분리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/add/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/add/AddPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/add/AddUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishDogAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishStampAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/StampDialogFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/CalendarDialog.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/HistoryOnClickListener.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/HistoryViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/WalkHistoryAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/WalkHistoryMapDialog.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/AllStampActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/AllStampAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/AllStampViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/GraphUtils.kt
  app/src/main/res/layout/activity_add.xml
  app/src/main/res/layout/activity_detail_pet.xml
  app/src/main/res/layout/activity_edit_pet.xml
  app/src/main/res/layout/activity_finish.xml
  app/src/main/res/layout/fragment_stamp_dialog_.xml
Labels: 🛠️ refactor

#216 산책 반려견 선택 UI 변경
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkDogAdapter.kt
  app/src/main/res/drawable/ic_check_box_24.xml
  app/src/main/res/drawable/ic_check_box_blank_24.xml
  app/src/main/res/layout/item_walk_dogs.xml
Labels: 🖌️ design, 🛠️ refactor

#218 fragment 내의 flow collect하는 코루틴 lifecycle 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
Labels: 🐞 bug

#214 firebase crashlytics 적용
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ⚙️ chore

#204 맵 내 현재 위치 버튼 줌 인/아웃에 맞추기
  app/src/main/res/layout/fragment_walk.xml
Labels: 🛠️ refactor

#207 home, history, navigationBar등 UI수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/WalkHistoryAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/res/drawable/ic_calendar_select.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_walk.xml
  app/src/main/res/drawable/ic_weather_rain.png
  app/src/main/res/drawable/ic_weather_slightly_cloudy.png
  app/src/main/res/drawable/ic_weather_snow.png
  app/src/main/res/drawable/ic_weather_sunny.png
  app/src/main/res/drawable/ic_weather_thunder.png
  app/src/main/res/drawable/rec_main_nav.xml
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_history_walk.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🖌️ design, ✨ feature, ❓ question

#229 [design] splash 이미지, logo이미지 바꾸기
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/splash_logo.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/styles.xml
Labels: 🖌️ design

#244 Stamp정보 리스트 받아오는 로직 구현
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/StampInfo.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StampRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StampInfoEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/StampRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampInfoListUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampInfoListUseCaseImpl.kt
Labels: ✨ feature

#231 refactor: 커스텀 버튼 없애고 setContentPadding으로 해결봤다.
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/res/layout/fragment_walk.xml
Labels: 🛠️ refactor

#227 [refactor]login 단일 activity로 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpFragment.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_log_in.xml
  app/src/main/res/layout/fragment_sign_up.xml
Labels: 🖌️ design, 🛠️ refactor

#241 최근 산책 몇 시간 전인지 UI 제공: 김찬교
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature, ❓ question, 🛠️ refactor

#219 산책 이력 이미지 공유 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/WalkHistoryAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/WalkHistoryMapDialog.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/WalkingImageTransformation.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/TextConverter.kt
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/img_map_default.xml
  app/src/main/res/layout/dialog_walk_history_map.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/file_paths.xml
  gradle/libs.versions.toml
Labels: ✨ feature

#224 산책 결과 화면에서 백버튼 눌렸을 때 다이얼로그 띄우기
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishActivity.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feature, 🎨 resource

#225 스탬프 획득 창 개선
  app/build.gradle.kts
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishStampViewPagerAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/StampDialogFragment.kt
  app/src/main/res/drawable/rec_dialog.xml
  app/src/main/res/layout/fragment_stamp_dialog_.xml
  app/src/main/res/layout/item_walk_finish_stamp.xml
  gradle/libs.versions.toml
Labels: ✨ feature

#255 [feat] 로그아웃, 회원 탈퇴 시 다이얼로그
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feature
