Repository nbc-final-team2/ddaraogae, pull requests merged in 2024-07, with the labels that each got.

#253 [refactor] 약관 view 통일
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypagePrivacyActivity.kt
  app/src/main/res/drawable/privacy_policy_1.png
  app/src/main/res/drawable/privacy_policy_2.png
  app/src/main/res/drawable/privacy_policy_3.png
  app/src/main/res/drawable/privacy_policy_4.png
  app/src/main/res/layout/activity_privacy.xml
  app/src/main/res/values/privacy.xml
Labels: 🖌️ design, 🛠️ refactor

#250 날씨 / 산책 도장 bar / history 화면 회전 / 반려견 나이 관련 버그 해결
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/add/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/WalkHistoryMapDialog.kt
  app/src/main/res/drawable/progress_bar_stamp.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 bug

#246 산책 리마인더 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/AlarmModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/DataSourceModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/DataStoreModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/RepositoryModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/local/AlarmDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/local/AlarmDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/AlarmMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/model/AlarmPreference.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AlarmRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/AlarmEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/AlarmRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/DeleteAlarmUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/DeleteAlarmUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetAlarmListUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetAlarmListUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertAlarmUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertAlarmUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateAlarmUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateAlarmUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/alarm_core/AlarmConstant.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/alarm_core/AlarmController.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/alarm_core/AlarmReceiver.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/AlarmModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/alarm/AlarmActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/alarm/AlarmAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/alarm/AlarmSetDialogFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/alarm/AlarmUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/alarm/AlarmViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/loading/LoadingDialog.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/res/drawable/bg_dialog_round.xml
  app/src/main/res/drawable/ic_delete_24.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/fragment_alarm_set_dialog.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_alarm.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ⚙️ chore, 🖌️ design, ✨ feature, 🎨 resource

#236 산책기록 더보기 기능
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/HistoryViewModel.kt
Labels: ✨ feature

#252 [refactor]반려견 페이지 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/MyPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/PetListAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/PetListFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/res/drawable/camera.png
  app/src/main/res/layout/activity_add.xml
  app/src/main/res/layout/activity_edit_pet.xml
  app/src/main/res/layout/activity_my_pet.xml
  app/src/main/res/layout/fragment_detail_pet.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_pet_list.xml
  app/src/main/res/layout/item_pet_list.xml
  app/src/main/res/values/strings.xml
Labels: 🖌️ design, 🛠️ refactor

#258 산책 화면 현재 위치 트래킹 해제 이후, 특정 조건(시간?) 달성 시 다시 트래킹하도록 처리: 김찬교
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
Labels: ✨ feature, 🛠️ refactor

#263 약간의 마커 정보창 수정, 카메라 영역 한국으로 제한
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
Labels: ✨ feature, 🛠️ refactor

#276 회원가입, 강아지 정보 추가, 수정 페이지 버튼 상태 관리
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/add/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpFragment.kt
  app/src/main/res/layout/activity_add.xml
  app/src/main/res/layout/activity_edit_pet.xml
Labels: 🐞 bug, ✨ feature

#267 산책 완료 화면에 강아지 이름이 같이 표시되도록 함
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishDogAdapter.kt
  app/src/main/res/layout/item_finish_dogs.xml
Labels: 🖌️ design, ✨ feature

#278 약관 등 문서를 text로 받아와 처리하기 / 개인정보처리 동의서에 현재 날짜 표시하기
  app/src/main/assets/doc_privacy_agreement
  app/src/main/assets/doc_privacy_rules
  app/src/main/assets/doc_user_term
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageAgreementPrivacy.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypagePrivacyActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageTermsActivity.kt
  app/src/main/res/drawable/agreement_privacy_policy_1.png
  app/src/main/res/drawable/privacy_policy_1.png
  app/src/main/res/drawable/privacy_policy_2.png
  app/src/main/res/drawable/privacy_policy_3.png
  app/src/main/res/drawable/privacy_policy_4.png
  app/src/main/res/drawable/terms_of_use_1.png
  app/src/main/res/drawable/terms_of_use_2.png
  app/src/main/res/drawable/terms_of_use_3.png
  app/src/main/res/drawable/terms_of_use_4.png
  app/src/main/res/drawable/terms_of_use_5.png
  app/src/main/res/drawable/terms_of_use_6.png
  app/src/main/res/layout/activity_agreement_privacy.xml
  app/src/main/res/layout/activity_privacy.xml
  app/src/main/res/layout/activity_terms_of_use.xml
  app/src/main/res/values/strings.xml
Labels: 🖌️ design, ✨ feature

#271 잔존 데이터 예외처리 완료
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 bug

#284 FinishActivity의 지도 버그 및 동적으로 padding 값을 변경하도록 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishActivity.kt
Labels: 🐞 bug, 🛠️ refactor

#285 EditText 외부 눌렀을 때 소프트 키보드 숨김처리
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/KeyboardCleaner.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/add/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
Labels: 🛠️ refactor

#288 코루틴 생명주기 리팩터링 내용 롤백 및 버그 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/PetListFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/AllStampFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/StampDetailFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
Labels: 🐞 bug, 🛠️ refactor

#290 [feat] 약관 전체 동의 기능
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpFragment.kt
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#268 DB 스키마 재 디자인 및 관련 로직 변경
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/WalkingDogDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/WalkingDto.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/FirebaseMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/WalkingRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/WalkingEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/WalkingRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertWalkingDataUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertWalkingDataUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/WalkingInfo.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/HistoryViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/TextConverter.kt
Labels: 🐞 bug, 🛠️ refactor

#293 비밀번호 노출 토글 작성 및 소프트 키보드 노출 시 리사이징 처리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/add/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/PasswordToggle.kt
  app/src/main/res/drawable/ic_visibility_grey_24.xml
  app/src/main/res/drawable/ic_visibility_off_grey_24.xml
  app/src/main/res/layout/fragment_log_in.xml
  app/src/main/res/layout/fragment_sign_up.xml
Labels: 🖌️ design, ✨ feature, 🛠️ refactor, 🎨 resource

#277 [refactor] 회원 탈퇴 로직 변경
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
  app/src/main/res/values/strings.xml
Labels: 🐞 bug, 🛠️ refactor

#296 반려견 정보 뒤로가기 버그 해결
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetFragment.kt
Labels: 🐞 bug

#295 Update README.md
  README.md
Labels: 📗 docs

#291 style: 주석 제거
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/finish/FinishActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkViewModel.kt
Labels: 📋 style

#279 home의 State들을 하나의 dataclass로 통합
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeUiState.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/StampDetailFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
Labels: 🛠️ refactor

#299 [bug] login, signup 버튼 state 버그 해결
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpFragment.kt
Labels: 🐞 bug

#300 Update README.md
  README.md
Labels: 📗 docs

#301 [bug]반려견 페이지 back 오류 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/MyPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/NullEvent.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/PetListFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
Labels: 🐞 bug

#308 반려견 정보 Add, Edit 시 이미지 런처 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/add/AddActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/edit/EditPetActivity.kt
Labels: 🛠️ refactor

#310 refactor/mypage
  app/src/main/res/drawable/ic_chevron_right.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_pet_list.xml
Labels: 🖌️ design

#318 Home 디자인 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/res/drawable/ic_information.xml
  app/src/main/res/drawable/ic_renewal.xml
  app/src/main/res/drawable/rec_main_nav.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🖌️ design, 🎨 resource

#317 산책 반려견 선택 여부 아이콘 배경 삭제
  app/src/main/res/layout/item_walk_dogs.xml
Labels: 🖌️ design

#322 로그인 시 없는 계정 예외처리
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#315 산책 리마인더 로직 수정
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/AlarmModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/DispatcherModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/local/AlarmDataSource.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/local/AlarmDataSourceImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/AlarmMapper.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/model/AlarmPreference.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AlarmRepositoryImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/AlarmEntity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/AlarmRepository.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/DeleteAlarmUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/DeleteAlarmUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetAlarmListUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetAlarmListUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertAlarmUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertAlarmUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateAlarmUseCase.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateAlarmUseCaseImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/alarm_core/AlarmController.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/alarm_core/AlarmReceiver.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/ItemChangedEventBusImpl.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/alarm/AlarmViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MyPageViewModel.kt
Labels: 🐞 bug, 🛠️ refactor

#324 산책그래프 오늘 날짜 표시
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/CustomXAxisRenderer.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/HistoryActivity.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/history/WalkHistoryAdapter.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
  app/src/main/res/layout/activity_history.xml
Labels: 🛠️ refactor

#314 구글 버튼 수정, mypage 피드백 수정
  app/src/main/res/drawable/google_login_box.png
  app/src/main/res/layout/fragment_log_in.xml
  app/src/main/res/layout/fragment_pet_list.xml
  app/src/main/res/values/strings.xml
Labels: 🛠️ refactor
